### ISSUE TITLE
Setting an enumflag with no default value

### ISSUE THREAD

**Issue by erezpaz125** [thediveo/enumflag#3] opened 2022-08-08 10:58 UTC
Hi, 
I wish to use this package for enum value verification for enum typed flags, however I do not wish for these flags to have a default value so that  if the user won't enter a required flag it will throw him an error.
Currently I couldn't figure out a way to do this since it seems that it is necessary to use Var/VarP which cause it to always have a default value. 
Is there some way to make this work that I missed out on?
Thanks in advance!

**Comment by thediveo** [comment] 2022-08-08 14:50
Do you have a concrete example of such a flag? So far, there is no implicit unset value, much in the same way as there is no unset bool or unset int, and so on. The README.md has an example of how to set the default value and I would expect that an explicit "none" default value could do the job?

Otherwise, nullable enums will need some major refactoring and break everything, so something for v2 maybe; or maybe a separate new nullable enum flag.

**Comment by erezpaz125** [comment] 2022-08-09 07:23
For example in the following screenshot "directory_service_type" is an enumflag, and I tried setting its default value to "none" as you suggested. It is also a required flag but I did not include it in the command line input, therefore I would wish to see it included in the "required flags ..." error message
![image](https://user-images.githubusercontent.com/73018591/183588756-db8eff10-1555-42b4-b7e5-4c94a92a851f.png)

I do not wish for the enums to be nullable per se, I just want the option to define them with no default value

**Comment by thediveo** [comment] 2022-08-09 13:06
Thank you very much for the example, that illustrates it for me very nicely!

This looks like the issue is two-fold:
1. mandatory flags: not covered by `spf13/pflag` itself, but only by `spf13/cobra`, see also [issue 502](https://github.com/spf13/cobra/pull/502).
2. the problem of a suppressed default "none" enum value.

I need to drill down further into 2, as I'm unsure to what extent there is support for suppressed default values.

**Comment by thediveo** [comment] 2022-08-09 19:57
In the process of implementing this feature I will introduce a change that will be in hopefully almost all use cases of scalar enum flags transparent: the next minor release of enumflag will leverage Go generics to provide compile-time type safety. This will require Go 1.18 or later, but please note that we now have 2 Go minor versions with generics support (and I don't support no more than the two most recent minor Go versions anyway).

**Comment by erezpaz125** [comment] 2022-08-10 11:10
Thank you very much for looking into this!
If I understood your last comment correctly you anticipate this issue to be fixed with the next release?

**Comment by thediveo** [comment] 2022-08-10 11:59
Correct; but it will be part of migrating the underlying implementation to Go generics. This ensures compile-time type safety checks and reduces the code basis.

**Comment by erezpaz125** [comment] 2022-08-11 12:07
Awesome thank you! Looking forward to it!
Do you by chance have a rough estimate when it might come out?

**Comment by thediveo** [comment] 2022-08-12 12:34
I've already made excellent progress in refactoring (to be found in the `no-default-value-3` branch) to a generics-based implementation. The slice-based unit tests now need to be carried over and the documentation updated, before finishing with the no-default handling. But I'm satisfied with the generics refactoring, as this really allowed me to drop several chunks of reflect-based runtime panicking ("Gotcha!"), so that the compiler now gets you before run.

As there are several downstream projects using `enumflag` this will become `v2` instead of breaking `v0`.

**Comment by thediveo** [comment] 2022-08-12 20:31
*crackle* the Eagle has landed *crackle*

Please use the semver v2 import path `github.com/thediveo/enumflag/v2` and check the documentation, the [no default value example](https://pkg.go.dev/github.com/thediveo/enumflag/v2#example-package-No_default_value) in particular.

**Closed as completed** 2022-08-12 20:37 UTC
